Repository SalehAhmed19/liya-baby-shop, pull requests merged in 2023-01, with the labels that each got.

#3 adding navbar and products on homepage
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Pages/Home/About/About.jsx
  client/src/components/Pages/Home/Banner/Banner.jsx
  client/src/components/Pages/Home/Blogs/Blogs.jsx
  client/src/components/Pages/Home/Brands/Brands.jsx
  client/src/components/Pages/Home/Faq/Faq.jsx
  client/src/components/Pages/Home/Home/Card1.jsx
  client/src/components/Pages/Home/Home/Home.jsx
  client/src/components/Pages/Home/Home/HomeTitle.jsx
  client/src/components/Pages/Home/Products/Products.jsx
  client/src/components/Pages/Home/RecomendsProduct/RecomendsProduct.jsx
  client/src/components/Shared/Footer/Footer.jsx
  client/src/components/Shared/Navbar/Navbar.jsx
  client/src/index.css
  client/tailwind.config.js
Labels: enhancement

#4 Ra/navbar#1
  README.md
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Pages/Home/About/About.jsx
  client/src/components/Pages/Home/Banner/Banner.jsx
  client/src/components/Pages/Home/Blogs/Blogs.jsx
  client/src/components/Pages/Home/Brands/Brands.jsx
  client/src/components/Pages/Home/Faq/Faq.jsx
  client/src/components/Pages/Home/Home/Card1.jsx
  client/src/components/Pages/Home/Home/Home.jsx
  client/src/components/Pages/Home/Home/HomeTitle.jsx
  client/src/components/Pages/Home/Products/Products.jsx
  client/src/components/Pages/Home/RecomendsProduct/RecomendsProduct.jsx
  client/src/components/Shared/Footer/Footer.jsx
  client/src/components/Shared/Navbar/Navbar.jsx
  client/src/index.css
  client/tailwind.config.js
Labels: enhancement

#5 Develop
  client/src/components/Pages/Home/Home/HomeTitle.jsx
  client/src/components/Pages/Home/RecomendsProduct/RecomendsProduct.jsx
Labels: enhancement

#6 Ra/product collection#2
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.js
  client/src/components/Pages/Home/About/About.jsx
  client/src/components/Pages/Home/Banner/Banner.jsx
  client/src/components/Pages/Home/Blogs/Blogs.jsx
  client/src/components/Pages/Home/Brands/Brands.jsx
  client/src/components/Pages/Home/Home/Home.jsx
  client/src/components/Pages/Home/Products/Products.jsx
  client/src/components/Pages/Home/RecomendsProduct/RecomendsProduct.jsx
  client/src/components/Shared/Footer/Footer.jsx
  client/src/components/Shared/Navbar/MyLinks.jsx
  client/src/components/Shared/Navbar/NavLinks.jsx
  client/src/components/Shared/Navbar/Navbar.jsx
  client/src/index.css
  client/src/index.js
Labels: enhancement

#7 some changes
  client/package-lock.json
Labels: enhancement

#8 Ra/product collection#2
  client/package-lock.json
  client/package.json
  client/src/components/Pages/Home/About/About.jsx
  client/src/components/Pages/Home/Banner/Banner.jsx
  client/src/components/Pages/Home/Blogs/Blogs.jsx
  client/src/components/Pages/Home/Brands/Brands.jsx
  client/src/components/Pages/Home/Brands/style.css
  client/src/components/Pages/Home/Faq/Faq.jsx
  client/src/components/Pages/Home/Home/Home.jsx
  client/src/components/Pages/Home/Products/style.css
  client/src/components/Pages/Home/RecomendsProduct/RecomendsProduct.jsx
  client/src/components/Shared/Navbar/NavLinks.jsx
  client/src/components/Shared/Navbar/Navbar.jsx
  client/src/index.css
  client/tailwind.config.js
Labels: enhancement

#10 login page designed
  client/src/App.js
  client/src/CSS/Login.css
  client/src/components/Pages/Authentication/Login/Login.jsx
  client/src/components/Shared/Navbar/Navbar.jsx
  client/tailwind.config.js
Labels: enhancement

#12 redesigned login page
  client/src/CSS/Login.css
  client/src/components/Pages/Authentication/Login/Login.jsx
  client/src/index.css
Labels: enhancement

#13 redesigned login page
  client/src/Assets/icon/Liya Baby Shop-3.png
  client/src/CSS/Login.css
  client/src/components/Pages/Authentication/Login/Login.jsx
  client/src/components/Shared/Navbar/Navbar.jsx
  client/tailwind.config.js
Labels: enhancement

#16 some changes
  client/src/Assets/images/liya-baby-shop.png
  client/src/components/Pages/Home/About/About.jsx
Labels: enhancement

#17 news letter section added
  client/src/components/Pages/Home/Home/Home.jsx
  client/src/components/Pages/Home/NewsLetter/NewsLetter.jsx
Labels: enhancement

#18 some changes
  client/src/components/Pages/Authentication/Login/Login.jsx
Labels: enhancement

#19 faq question added
  client/src/components/Pages/Home/Faq/Faq.jsx
  client/src/components/Pages/Home/Faq/FaqQuestion.jsx
Labels: enhancement

#20 products added
  client/src/components/Pages/Home/Home/Card2.jsx
  client/src/components/Pages/Home/Products/Products.jsx
  client/src/components/Pages/Home/RecomendsProduct/RecomendsProduct.jsx
  client/src/components/Shared/Navbar/Navbar.jsx
Labels: enhancement

#21 product card
  client/src/components/Pages/Home/Banner/Banner.jsx
  client/src/components/Pages/Home/RecomendsProduct/RecomendsProduct.jsx
Labels: bug, enhancement

#22 card added
  client/src/components/Pages/Home/RecomendsProduct/RecomendsProduct.jsx
Labels: enhancement

#23 card 2 added
  client/src/components/Pages/Home/Brands/Brands.jsx
  client/src/components/Pages/Home/Home/Card2.jsx
  client/src/components/Pages/Home/Home/Card2.module.css
  client/src/components/Pages/Home/Home/Home.jsx
  client/src/components/Pages/Home/Products/Products.jsx
  client/src/components/Pages/Home/RecomendsProduct/RecomendProduct.module.css
  client/src/components/Pages/Home/RecomendsProduct/RecomendsProduct.jsx
Labels: enhancement

#25 some changes
  client/src/components/Pages/Home/Home/Card2.jsx
Labels: enhancement

#27 updated navbar, banner, recomended product, card-2, info
  client/src/Assets/images/bannerImg-01.jpg
  client/src/Assets/images/bannerImg-02.jpg
  client/src/Assets/images/bannerImg-03.jpg
  client/src/Assets/images/bannerImg-04.jpg
  client/src/Assets/images/easy.svg
  client/src/Assets/images/free.svg
  client/src/Assets/images/safety.svg
  client/src/Assets/images/secure.svg
  client/src/components/Pages/Home/Banner/Banner.jsx
  client/src/components/Pages/Home/Faq/Faq.jsx
  client/src/components/Pages/Home/Faq/FaqQuestion.jsx
  client/src/components/Pages/Home/Home/Card2.jsx
  client/src/components/Pages/Home/Home/Home.jsx
  client/src/components/Pages/Home/Home/HomeTitle.jsx
  client/src/components/Pages/Home/Products/Products.jsx
  client/src/components/Pages/Home/RecomendsProduct/RecomendsProduct.jsx
  client/src/components/Shared/Footer/Footer.jsx
  client/src/components/Shared/Info/Info.jsx
  client/src/components/Shared/Navbar/Navbar.jsx
  client/tailwind.config.js
Labels: enhancement, Customization

#28 navbar color correction and card photo updated
  client/src/Assets/dress/dress-1.webp
  client/src/Assets/dress/dress-2.webp
  client/src/Assets/dress/dress-3.webp
  client/src/Assets/dress/dress-4.webp
  client/src/Assets/dress/dress-5.webp
  client/src/Assets/dress/dress-6.webp
  client/src/components/Pages/Home/Home/Card2.jsx
  client/src/components/Pages/Home/RecomendsProduct/RecomendsProduct.jsx
  client/src/components/Shared/Navbar/NavLinks.jsx
  client/src/components/Shared/Navbar/Navbar.jsx
Labels: enhancement, Customization

#33 brands section added
  client/src/Assets/brands/brand1.avif
  client/src/Assets/brands/brand10.avif
  client/src/Assets/brands/brand2.avif
  client/src/Assets/brands/brand3.avif
  client/src/Assets/brands/brand4.avif
  client/src/Assets/brands/brand5.avif
  client/src/Assets/brands/brand6.avif
  client/src/Assets/brands/brand7.avif
  client/src/Assets/brands/brand8.avif
  client/src/Assets/brands/brand9.avif
  client/src/components/Pages/Home/Brands/Brands.jsx
  client/src/components/Pages/Home/Brands/style.css
  client/src/components/Shared/Info/Info.jsx
Labels: enhancement

#35 Sam/review customization#26
  client/package-lock.json
  client/package.json
  client/src/components/Pages/Home/Banner/Banner.jsx
Labels: enhancement

#36 some changes
  client/src/App.js
  client/src/components/Pages/Category/Categories.jsx
  client/src/components/Pages/Home/About/About.jsx
  client/src/components/Pages/Home/Blogs/Blogs.jsx
  client/src/components/Pages/Home/Home/Home.jsx
Labels: Customization

#37 some changes
  client/src/components/Pages/Home/Products/Products.jsx
Labels: Customization

#38 about us content added
  client/src/components/Pages/Home/About/About.jsx
  client/src/components/Pages/Home/Products/Products.jsx
  client/src/components/Shared/Footer/Footer.jsx
Labels: Customization

#39 about us content added
  client/src/components/Pages/Home/About/About.jsx
Labels: Customization

#41 category added
  client/src/Assets/categories/diapar.jpg
  client/src/Assets/categories/man.jpg
  client/src/Assets/categories/offer.jpg
  client/src/Assets/categories/other.jpg
  client/src/Assets/categories/woman.jpg
  client/src/components/Pages/Category/Categories.jsx
Labels: enhancement

#42 banner carosel automated
  client/src/components/Pages/Home/Banner/Banner.jsx
Labels: enhancement, Customization

#43 category page designed
  client/src/App.js
  client/src/components/Pages/Category/BabyDiaper.jsx
  client/src/components/Pages/Category/BabyDressBoy.jsx
  client/src/components/Pages/Category/BabyDressGirl.jsx
  client/src/components/Pages/Category/Categories.jsx
  client/src/components/Pages/Category/ManClothing.jsx
  client/src/components/Pages/Category/NewBornEssentials.jsx
  client/src/components/Pages/Category/OfferItems.jsx
  client/src/components/Pages/Category/WomenDress.jsx
Labels: enhancement

#44 some changes
  client/src/components/Pages/Category/BabyDiaper.jsx
  client/src/components/Pages/Category/Filter.jsx
  client/src/components/Pages/Category/FilterBtn.jsx
  client/src/components/Pages/Category/ProductCard.jsx
  client/src/components/Pages/Category/SortingBar.jsx
  client/src/components/Pages/Category/SortingBtn.jsx
Labels: duplicate

#46 some changes
  client/src/components/Shared/Navbar/MyLinks.jsx
  client/src/components/Shared/Navbar/NavLinks.jsx
Labels: Customization

#48 Some Customization
  client/src/components/Pages/Category/BabyDressBoy.jsx
  client/src/components/Pages/Category/BabyDressGirl.jsx
  client/src/components/Pages/Category/FilterBtn.jsx
  client/src/components/Pages/Category/ManClothing.jsx
  client/src/components/Pages/Category/NewBornEssentials.jsx
  client/src/components/Pages/Category/OfferItems.jsx
  client/src/components/Pages/Category/WomenDress.jsx
  client/src/components/Shared/Footer/Footer.jsx
  client/src/components/Shared/Navbar/MyLinks.jsx
  client/src/components/Shared/Navbar/NavLinks.jsx
  client/src/components/Shared/Navbar/Navbar.jsx
Labels: enhancement, Customization

#51 some changes
  client/src/components/Shared/Footer/Footer.jsx
Labels: Customization

#55 Sam/category#40
  client/src/App.js
  client/src/components/Pages/Category/BabyDiaper.jsx
  client/src/components/Pages/Category/ProductCard.jsx
  client/src/components/Pages/Category/ProductDetails/ProductDetails.jsx
  client/src/components/Pages/Category/ProductDetails/ProductImg.jsx
  client/src/components/Pages/Category/ProductDetails/ProductInfo.jsx
  client/src/components/Pages/Category/ProductDetails/ProductQYTnPrice.jsx
Labels: enhancement

#57 Product detail
  client/src/App.js
  client/src/components/Pages/Category/BabyDiaper.jsx
  client/src/components/Pages/Category/ProductCard.jsx
  client/src/components/Pages/Category/ProductDetails/ProductDetails.jsx
  client/src/components/Pages/Category/ProductDetails/ProductImg.jsx
  client/src/components/Pages/Category/ProductDetails/ProductInfo.jsx
  client/src/components/Pages/Category/ProductDetails/ProductQYTnPrice.jsx
Labels: duplicate

#58 product image magnified
  client/package-lock.json
  client/package.json
  client/src/Assets/Zoom/dress-1-1200.jpg
  client/src/Assets/Zoom/dress-1-300.jpg
  client/src/components/Pages/Category/ProductDetails/ProductDetails.jsx
  client/src/components/Pages/Category/ProductDetails/ProductImg.jsx
Labels: enhancement

#60 cart page designed
  client/src/App.js
  client/src/Assets/PaymentsIcon/COD1.svg
  client/src/Assets/PaymentsIcon/Maestro1.svg
  client/src/Assets/PaymentsIcon/Mastercard1.svg
  client/src/Assets/PaymentsIcon/Net_Banking1.svg
  client/src/Assets/PaymentsIcon/Rupay1.svg
  client/src/Assets/PaymentsIcon/Visa1.svg
  client/src/Assets/PaymentsIcon/upi.svg
  client/src/components/Pages/Home/Cart/Cart.jsx
  client/src/components/Pages/Home/Cart/CartBar.jsx
  client/src/components/Pages/Home/Cart/CartIncDec.jsx
  client/src/components/Pages/Home/Cart/CheckoutBtn.jsx
  client/src/components/Pages/Home/Cart/OfferBar.jsx
  client/src/components/Pages/Home/Cart/ProductInformation.jsx
  client/src/components/Shared/Navbar/Navbar.jsx
Labels: enhancement

#61 some changes
  client/src/components/Pages/Home/Cart/ProductInformation.jsx
Labels: bug, enhancement, Customization

#62 some changes
  client/src/components/Pages/Home/Cart/ProductInformation.jsx
Labels: bug, enhancement, Customization

#67 basic server setup completed
  server/index.js
  server/package-lock.json
  server/package.json
Labels: enhancement

#70 basic server setup completed
  client/src/components/Pages/Home/RecomendsProduct/RecomendsProduct.jsx
Labels: enhancement

#74 some changes
  client/src/components/Pages/Home/RecomendsProduct/RecomendsProduct.jsx
Labels: Customization
